# Generated by Django 4.2.6 on 2023-10-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
